#!/bin/sh

chmod +x dna.py
./dna.py ATGCCCCGTATTAGACGATAGACGTTAGATTAGATAG
./dna.py CTAGATAGCATAGTACATTAGATTAGATTAGATTAGATTAGATTATATTATATATATATAGGAC
./dna.py AGATCGATCGTAGCTGATCGCTTAAAAATCGCTAGATAGCTTCGCT
./dna.py AAAATAGGATCATTAGACGATTGACGATTGGAACCAGTACACAT
